### ISSUE TITLE
SEO Assessment

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#147]
Client had an SEO firm assess the website. I want to give them an overview of our recommendations sometime the week of Dec 17-21.

**Comment by cunning-folk** [comment]
I would love to get the client a scope of work (if need be) to solve for these issues sometime the week of Dec 17-21.

PDF attached

[Technical SEO Analysis_ elevate360.pdf]

(https://github.com/CunningFolkDev/elevate360_website/files/2677245/Technical.SEO.Analysis_.elevate360.pdf)

**Comment by gblakeman** [comment]
@cunning-folk Took a look – as far as stuff related to the build/code of the site, they didn’t find much. And most of the things that they flagged, I disagree with, of course.

Here’s the [PDF with my notes](https://github.com/CunningFolkDev/elevate360_website/files/2688088/Technical.SEO.Analysis_.elevate360_annotated.pdf).

Easy code-related fixes that I can turn into actionable issues:

* Add a blank `robots.txt` file to [allow all indexing](https://stackoverflow.com/questions/4276957/how-to-configure-robots-txt-to-allow-everything)
* Add index/follow [`meta` tags](https://www.metatags.org/meta_name_robots) to allow all indexing
* Add `meta` keywords field and hook into CMS (although it is [literally ignored](https://datadrivenlabs.io/blog/meta-keyword-tag-google-2018/) by Google and possibly used as a spam flag by other search engines.
* Find images on the site that do not yet have `alt` tags. Add + hook into CMS.
* Add site to Google Webmaster tools + verify
* Add standard RSS feed to the blog

I can’t imagine any of this taking more than 2-3 hours, total (likely a lot less), and I’m about half an hour in as far as reading the report and scoping things.

Anything related to the “off-page ranking” as this SEO company calls it (Page/Domain Authority, Backlinks, site traffic, 3rd-party rankings) are out of our control and require paid/unpaid advertising and seeding of content elsewhere on the internet.

Anything related to on-page content optimization (seeding keywords, manipulating title tags, etc.) is something a good copywriter should do and not the client, design, or dev team. If you’re trying to ensure they hire you instead of this SEO firm, I’d suggest you lobby for a good marketing copywriter to audit the site content as part of the budget.

Let me know if you’d like me to convert this list into some issues to work on.

**Comment by cunning-folk** [comment]
@gblakeman Go ahead and get these changes scheduled. Shall we say a Friday delivery date? Thanks for taking time to have a look!

**Comment by jeremylenz** [comment]
@gblakeman Once the issues are created, feel free to assign any to me that you don't feel like doing.

**Comment by gblakeman** [comment]
Closing this since I created issues for everything.

@jeremylenz I added them to the project Backlog and assigned you.
