### ISSUE TITLE
Call out bug on 'Our Technology'

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#166]

**Comment by cunning-folk** [comment]
https://elevate360.com/why-elevate360/our-technology/

Looks like the white callout button needs a diff color text?
 
Please see screenshot.

<img width="1335" alt="screen shot 2019-01-21 at 3 59 02 pm" src="https://user-images.githubusercontent.com/31627480/51502951-b4abc780-1d95-11e9-8f47-3e74df845019.png">

**Comment by jeremylenz** [comment]
@cunning-folk  After investigating, it turns out that the text wasn't actually there.  It was a bug from when I was removing all the hard-coded phone numbers.  Had to add some logic in to avoid hard-coding the phone number again. 

The button text should now say "Call Now" and link to the phone number.  Let me know if any issues remain.
