### ISSUE TITLE
404 Errors

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#170]

**Comment by cunning-folk** [comment]
@jeremylenz can you please look at https://elevate360.com/services/how-we-treat and https://elevate360.com/services/therapies-used 

I suspect that when you added the 'groups' there may have been an issue?

**Comment by jeremylenz** [comment]
Looks like those didn't get changed when we moved those pages in the Nav in #160 .  I should run `rake html_proofer` more often.

Now that those pages are in a different section, we may want to think about altering the Services main page since those old blurbs are still there?  For now, I just fixed the links so they lead to the new locations and there's no more 404 errors.

Published & passing now.. let me know if you still see issues.
