### ISSUE TITLE
Publish Failure // Siteleaf

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#196]
The client reports failure to post a press release to media and update the 'Groups' functionality.

I tried to publish and Sitekeal returned this error. Looks like last successful publish was 22 days ago.

```Liquid Exception: couldn't find file '' in `about-us/resources/media.markdown' Checked in these paths: /_uploads /assets/css /assets/fonts /assets/images /assets/videos /assets/audios /assets/components /assets/javascript /assets/video /assets/audio /assets/image /assets/img /assets/js /_assets/css /_assets/fonts /_assets/images /_assets/videos /_assets/audios /_assets/components /_assets/javascript /_assets/video /_assets/audio /_assets/image /_assets/img /_assets/js /css /fonts /images /videos /audios /components /javascript /audio /video /image /img /js /.jekyll-cache/assets/proxied in /_layouts/resources_list.html
 (RuntimeError)```

**Comment by jeremylenz** [comment]
@cunning-folk Looks like the problem was in the file `elevate360-announces-name-change-to-wholeview-wellness-to-reflect-broader-healthcare-commitment.markdown`.

That collection requires every item to have a value specified for `image`, and this file didn't have one. 
I added an image and it seems to work now.  I did get Siteleaf to preview successfully.  See if the publish works for you now.

**Comment by jeremylenz** [comment]
@cunning-folk I went ahead and published and it was successful.  I also added default fields for `image` and `link` in that collection so that it doesn't happen next time.  Closing this issue for now.
