### ISSUE TITLE
Bug with a Media Post

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#219]
@jeremylenz 

This post doesnt seem to be formatted in a way so it shows up in the CMS

https://github.com/CunningFolkDev/elevate360_website/blob/master/_resources-media/Interview%20with%20Wholeview%20Wellness%20Psychologist%20Dr.%20Kamala%20Greene%20Genece

https://manage.siteleaf.com/sites/5cbe1b4fd60bac49a83f76d8/collections/resources-media

The client notes the layout for this article looked wonky and when i logged in to Siteleaf, it doesn't render at all as an item to be edited.

Any help appreciated!

**Comment by jeremylenz** [comment]
The file was named
```
Interview with Wholeview Wellness Psychologist Dr. Kamala Greene Genece
```

It didn't have a markdown extension, so Siteleaf didn't know what to do with it.  I renamed it
```
Interview with Wholeview Wellness Psychologist Dr Kamala Greene Genece.markdown
```
and it looks like it's in Siteleaf now.

For reference, other files are usually named like this:
```
how-a-popular-opioid-addiction-medication-helped-contribute-to-josh-gibsons-long-term-recovery-plan.markdown
```
with hyphens instead of spaces, and a `.markdown` extension. Not sure how this file got named so differently, but it was the lack of `.markdown` at the end that was causing the problem, so I didn't change anything else.

**Comment by cunning-folk** [comment]
Far out. I wish I knew how they made that happen.

Thanks for the fix!
