### ISSUE TITLE
Input on Image Compression Strategy

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#81]

**Comment by lukemiller** [comment]
FWIW, the current images are "retina" @2x sized.  There are a couple solutions where we would only serve those if device width or pixel density required, and serve a smaller version instead.  

Is that kind of what you're thinking?

**Comment by cunning-folk** [comment]
@lukemiller I saw this service that the Siteleaf creator recommended. Seems possibly helpful. https://www.imgix.com/

**Comment by lukemiller** [comment]
Imgix is nice, I've used it on a couple projects.

**Comment by gblakeman** [comment]
TBH, my strategy is usually to wing it and find a happy medium rather than obsess over serving a bunch of different size variants.

For photographs, literal 2x sizing isn’t usually necessary, so I shoot for roughly 1.75x-1.5x with 60-ish% JPEG compression.

The downside to my approach is that it’s all manual. Integrating a service like imgix would prevent the client from adding crazy-huge images in the future.

**Comment by jeremylenz** [comment]
We should still do this someday.  The HTML [`<picture>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) element should come in handy.  Closing the issue for now.
